# Generated by Django 5.1.3 on 2024-12-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('verwaltung', 'Verwaltung'), ('standortleitung', 'Standortleitung'), ('gruppenleitung', 'Gruppenleitung')], max_length=20),
        ),
    ]
