# Generated by Django 5.1.3 on 2024-12-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('verwaltung', 'Verwaltung'), ('standortleitung', 'Standortleitung'), ('gruppenleitung', 'Gruppenleitung'), ('admin', 'Admin')], max_length=20),
        ),
    ]
