# Generated by Django 5.1.3 on 2025-01-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('verwaltung', 'Verwaltung'), ('standortleitung', 'Standortleitung'), ('gruppenleitung', 'Gruppenleitung'), ('admin', 'Admin')], default='gruppenleitung', max_length=20),
        ),
    ]
