# Generated by Django 5.1.3 on 2025-01-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_group_id_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group_id',
            new_name='incharge_group_id',
        ),
    ]
