# Generated by Django 5.1.3 on 2025-01-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_group_id_user_incharge_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='incharge_group_id',
            new_name='group_id',
        ),
    ]
