# Generated by Django 5.1.3 on 2025-02-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_incharge_group_id_user_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('verwaltung', 'Verwaltung'), ('standortleitung', 'Standortleitung'), ('gruppenleitung', 'Gruppenleitung'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
